/**
 * Vendors a flag for every glyph, twice.
 *
 * SOURCE. lipis/flag-icons, which redraws every national flag as a clean 4:3 SVG. The
 * flags themselves are public domain — a national flag is a state emblem, not a work
 * anyone holds copyright in — and the redrawings are MIT. See NOTICE.
 *
 * TWO TIERS, because one size genuinely does not fit. The SVG scales to anything and is
 * what you want on a badge; it is also wildly uneven, because a flag with a coat of arms
 * on it is a coat of arms. Half of them are under a kilobyte and seven are over fifty,
 * with Serbia at 177KB. Per-country modules mean that lands only on whoever asks for
 * Serbia — but at glyph size it buys nothing: 177KB to draw a mark the size of a letter,
 * where six pixels of detail survive. So there is also a 48×36 raster, ~700 bytes flat,
 * which is what you want when the flag is a fill inside a silhouette.
 *
 * Rasterising is done here rather than left to the consumer because it is the only step
 * that needs a renderer, and a package that made you install sharp to draw a flag would
 * not be worth installing.
 *
 *   node scripts/build-flags.mjs
 */
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = 'https://raw.githubusercontent.com/lipis/flag-icons/main/flags/4x3';
const SVG_OUT = join(root, 'generated', 'flag');
const PNG_OUT = join(root, 'generated', 'flag-px');

/** Twice the ~19px a glyph is drawn at. Anything finer is thrown away by the scaler. */
const WIDTH = 48;
const HEIGHT = 36;
/** Enough parallelism to be quick, little enough to be polite. */
const LANES = 8;

const require = createRequire(join(root, 'package.json'));
const sharp = require('sharp');

/* Conservative: the prolog and the comments carry nothing a browser needs, and the
   whitespace between tags is the only other free saving. Nothing inside a tag is
   touched — flag SVGs use gradients and clip ids, and rewriting them is how you break
   one silently. */
const tidy = (svg) =>
  svg
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/>\s+</g, '><')
    .trim();

/**
 * A JS string literal that does not fight the content. `JSON.stringify` escapes every
 * double quote, and an SVG is mostly double quotes — 38KB of backslashes across the flag
 * set, for nothing. Single quotes are rare in markup and common in nothing else here.
 */
const quote = (text) =>
  `'${text.replace(/[\\'\n\r\u2028\u2029]/g, (c) => ({ '\n': '\\n', '\r': '\\r', '\u2028': '\\u2028', '\u2029': '\\u2029' })[c] ?? `\\${c}`)}'`;

const { CODES } = await import(join(root, 'generated', 'codes.js'));

await rm(SVG_OUT, { recursive: true, force: true });
await rm(PNG_OUT, { recursive: true, force: true });
await mkdir(SVG_OUT, { recursive: true });
await mkdir(PNG_OUT, { recursive: true });

const made = [];
const missing = [];
let svgBytes = 0;
let pngBytes = 0;

async function one(code) {
  const lower = code.toLowerCase();
  const response = await fetch(`${SOURCE}/${lower}.svg`);
  if (!response.ok) {
    missing.push(code);
    return;
  }
  const svg = tidy(await response.text());
  /* The density is what the SVG is rendered at before it is scaled down; too low and an
     emblem is aliased away before the resize can average it into anything. */
  const png = await sharp(Buffer.from(svg), { density: 400 })
    .resize(WIDTH, HEIGHT, { fit: 'fill' })
    .png({ compressionLevel: 9, palette: true })
    .toBuffer();

  await writeFile(
    join(SVG_OUT, `${lower}.js`),
    `// ${code} — generated by scripts/build-flags.mjs from lipis/flag-icons. Do not edit.\n` +
      `export const flag = ${quote(svg)};\nexport default flag;\n`,
  );
  await writeFile(
    join(PNG_OUT, `${lower}.js`),
    `// ${code} — generated by scripts/build-flags.mjs, ${String(WIDTH)}×${String(HEIGHT)}. Do not edit.\n` +
      `export const flag = 'data:image/png;base64,${png.toString('base64')}';\nexport default flag;\n`,
  );
  made.push(code);
  svgBytes += svg.length;
  pngBytes += png.length;
}

const queue = [...CODES];
await Promise.all(
  Array.from({ length: LANES }, async () => {
    for (let code = queue.shift(); code !== undefined; code = queue.shift()) await one(code);
  }),
);
made.sort();

const registry = (name, dir) =>
  `// Generated by scripts/build-flags.mjs. Do not edit.\nexport const ${name} = {\n` +
  made.map((c) => `  ${c}: () => import('./${dir}/${c.toLowerCase()}.js'),`).join('\n') +
  `\n};\n`;

/* One declaration per tier — see the note in build-shapes.mjs. */
for (const dir of ['flag', 'flag-px']) {
  await writeFile(
    join(root, 'generated', `${dir}.d.ts`),
    `export declare const flag: string;\nexport default flag;\n`,
  );
}

await writeFile(join(root, 'generated', 'flag-registry.js'), registry('flags', 'flag'));
await writeFile(
  join(root, 'generated', 'flag-registry.d.ts'),
  `export declare const flags: Record<string, () => Promise<{ flag: string }>>;\n`,
);
await writeFile(join(root, 'generated', 'flag-px-registry.js'), registry('flagsPx', 'flag-px'));
await writeFile(
  join(root, 'generated', 'flag-px-registry.d.ts'),
  `export declare const flagsPx: Record<string, () => Promise<{ flag: string }>>;\n`,
);

console.log(
  `build-flags: ${String(made.length)} flags — ${String(Math.round(svgBytes / 1024))}KB of SVG, ` +
    `${String(Math.round(pngBytes / 1024))}KB of PNG (${String(Math.round(pngBytes / made.length))}B each)`,
);
if (missing.length > 0) console.warn(`  no flag for: ${missing.join(' ')}`);
